swagger: '2.0'
host: localhost:3000
basePath: "/"
schemes:
- http
info:
  title: Playtime API
  version: '0.1'
tags: []
paths:
  "/api/users":
    get:
      summary: Get all userApi
      operationId: getApiUsers
      description: Returns details of all userApi
      tags:
      - api
      responses:
        '200':
          schema:
            "$ref": "#/definitions/UserArray"
          description: Successful
definitions:
  UserDetails:
    type: object
    properties:
      firstName:
        type: string
        example: Homer
      lastName:
        type: string
        example: Simpson
      email:
        type: string
        example: homer@simpson.com
        x-format:
          email: true
      password:
        type: string
        example: secret
      _id:
        type: string
        x-alternatives:
        - type: string
        - "$ref": "#/x-alt-definitions/_id"
      __v:
        type: number
    required:
    - firstName
    - lastName
    - email
    - password
  UserArray:
    type: array
    items:
      "$ref": "#/definitions/UserDetails"
x-alt-definitions:
  _id:
    type: object
